version: 2.0
jobs:
  build:
    macos:
      xcode: "10.0.0"
    environment:
      TERM: xterm
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: |
            brew install automake libtool gmp mpfr pkg-config pandoc maven opam z3
            make
  test:
    macos:
      xcode: "10.0.0"
    environment:
      TERM: xterm
    steps:
      - checkout
      - run:
          name: Test parsing
          command: |
            brew install automake libtool gmp mpfr pkg-config pandoc maven opam z3
            make
            make test-parse 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
